package model.menu;

public enum MenuState {
		QUIT_BUTTON_PRESSED,
		QUIT_BUTTON_RELEASED,
		START_BUTTON_PRESSED,
		START_BUTTON_RELEASED,
		CURSOR_ON_QUIT,
		CURSOR_ON_START,
		DEFAULT,
		START_DEFAULT,
		QUIT_DEFAULT,
		AUIDO_ON_DEFAULT,
		AUDIO_ON_HOVER,
		AUDIO_ON_PRESSED,
		AUDIO_ON_RELEASED,
		AUDIO_OFF_DEFAULT,
		AUDIO_OFF_HOVER,
		AUDIO_OFF_PRESSED,
		AUDIO_OFF_RELEASED

}
