package model.menu;

public enum MenuState {
		QUIT_BUTTON_PRESSED,
		QUIT_BUTTON_RELEASED,
		START_BUTTON_PRESSED,
		START_BUTTON_RELEASED,
		CURSOR_ON_QUIT,
		CURSOR_ON_START,
		DEFAULT,
		START_DEFAULT,
		QUIT_DEFAULT

}
